defaults: &defaults
  docker:
    - image: tailor/docker-libvips:node-8.6

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: tailor/docker-libvips:node-8.6
    steps:
      - run:
          name: install deps
          command: apt-get update -y; apt-get install git build-essential -y
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: update lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: gatsby build
          command: npm run build
      - run:
          name: upload lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-upload
      - run:
          name: copy ci config
          command: cp -r .circleci/ ./public/.circleci/
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - package-lock.json
            - .cache
            - public
  deploy:
      <<: *defaults
      docker:
        - image: circleci/node:8.6.0
      steps:
        - run:
            name: install deps
            command: apt-get update -y; apt-get install git -y
        - checkout
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - attach_workspace:
            at: /workspace/dist
        - run:
            name: git config
            command: git config --global user.email "deploy@circleci.com" && git config --global user.name "Circle CI"
        - run:
            name: gh-pages deploy
            command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
